### ISSUE TITLE
Option limit dosent work ;) 

### ISSUE THREAD

**Issue by 3G-IMMO-Sebastien** [loilo/Fuse#109]

**Comment by loilo** [comment]
Hey @3G-IMMO-Sebastien.

I'd love to help you fixing your problem, but I can't reproduce it, which is mostly because I have no idea what exactly you were trying to do.

Open source maintainers put a lot of time into offering you a program which works and which you can use for free, so I'd like to ask you to return the favor and take your time to write a bug report that contains a code example, what result you get from it and why it's not what you expected it to be. 🙂

**Comment by 3G-IMMO-Sebastien** [comment]
Hey @loilo,

Thank you for your reply! 

My apologies, everything is working perfectly. 

I added the "limit" option in "new Fuse()" instead of integrating it into the search() function.

Thank you for your work, I am adding a star to your repository.  ;)
