### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by vdgvince2** [loilo/Fuse#21]
Dear,

The library is great and the precision is very good. However, i have performances issues.

I'm running the tool on a list of 15,000 entries (2-3 words per entry, 1 field only) that i want to fuzzy against ifself. 
Here is my configuration

	$thresholdFuzzy = 0.6; // lower down that value to be more strict. 0 = exact match
	$FuzzyParameters = [
	  "keys" => [ "keywordName"],
	  "includeScore" => true,			
	  "maxPatternLength" => 32,
	  "threshold" => $thresholdFuzzy,
	  "minMatchCharLength" => 1
	];

	$fuse = new \Fuse\Fuse($dataToFuzzyNoExactMatch, $FuzzyParameters);
	$results = $fuse->search($kw);

I executed a loop of fuzzy on (the first) 100 entries compared to 15,000.
It took 500 seconds to compute.

Any idea how i can improve the speed please?

**Comment by loilo** [comment]
Hey,

to my knowledge, this is mainly a limition of the PHP runtime. 15,000 records is not a small number and this library does not even keep a search index.

I've investigated this kind of performance issue more deeply in https://github.com/loilo/Fuse/issues/18#issuecomment-477526586 and have come to the conclusion that it's probably not possible to improve in PHP land, at least not if I want to keep this a port of [Fuse.js](https://fusejs.io).

Mentioning Fuse.js, I've already suggested

* using Fuse.js instead with the V8js PHP extension, if you have the technical setup to install PHP extensions. Fuse.js in Node.js/V8 has a *much* better performance, just because that engine is way more advanced than the PHP interpreter. See https://github.com/loilo/Fuse/issues/8#issuecomment-389274768
* using a completely different fuzzy search approach with a proper database backing if applicable, e.g. `SOUNDEX`. See https://github.com/loilo/Fuse/issues/18#issuecomment-520488297

Sorry, I can't help you further with that.
