### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Lukasss93** [loilo/Fuse#29]
Hi! When will be released a stable version with PHP 8 support?

**Comment by loilo** [comment]
Good point. Going to get one out right now. :)

**Comment by loilo** [comment]
PHP 8 support is out. Had to do it in a major release (4.0.0) because support for PHP 5.6 to 7.2 has been dropped as well. (The library's code itself has not changed, so if you make Composer ignore Fuse's PHP version constraints, it should still run fine. But I don't test against old PHP versions any longer and I won't restrict myself to PHP 5 syntax in future changes.)
