### ISSUE TITLE
PHP 5.3

### ISSUE THREAD

**Issue by baldzilla** [Loilo/Fuse#9]
Can I use this with php 5.3 if I change all array constructs from [] to array()?
Would there be any other 5.3 limitations?

**Comment by Loilo** [comment]
I haven't tried that at all. However, I took a quick look at all new features since PHP 5.4 and Fuse at least uses the following:

* PHP 5.4: Array literals `[]`, as you already observed
* PHP 5.6: [Rest parameters](https://github.com/Loilo/Fuse/blob/master/src/Fuse.php#L432)
* PHP 5.6: [`use function`](https://github.com/Loilo/Fuse/blob/master/src/Fuse.php#L4-L5)
